### ISSUE TITLE
[feature request] show big square color preview.

### ISSUE THREAD

**Issue by shaeinst** [uga-rosa/ccc.nvim#13]
selected color is preview by color code itself. it would be nice if there would be big square color preview. something like below
![Untitled](https://user-images.githubusercontent.com/41078534/190899955-f3fae4d5-985d-4bdd-b869-a76adfad7a4f.png)

**Comment by uga-rosa** [comment]
Even at a quick glance, I see little benefit in implementing this, despite the many considerations such as size, where to put it out, fallback if it cannot be put out due to lack of space, and so on. Might make it a little easier to see?
The bottom line display is customizable (`ccc-option-output-line`), but is that not enough?

**Comment by shaeinst** [comment]
if I'm selecting color then, most of my focus are going to be on preview color. And square/rectangle preview would be easy for brain.

**Comment by uga-rosa** [comment]
I am the one who will do the maintenance and responds to issues for this feature. So I do not want to include it.
I added g:ccc_color instead, so feel free to set it yourself. Or you can share it on the wiki.
