### ISSUE TITLE
[Feature request] Command/API to convert color format directly

### ISSUE THREAD

**Issue by gegoune** [uga-rosa/ccc.nvim#22]
Hi, perhaps your plugin already has internal logic that could be exposed to provide functionality similar to that of [NTBBloodbath/color-converter.nvim](https://github.com/NTBBloodbath/color-converter.nvim)? What do you think?

**Comment by uga-rosa** [comment]
What you want to do is `<Cmd>CccPick<CR>o<CR>`, right? You can achieve this with a mapping, but I wonder if I should create a dedicated command.

**Comment by gegoune** [comment]
Ah, this is true. Not sure if anything needs to be added now. But perhaps your plugin will have one day an api that will allow for some scripting using its functionality?

**Comment by uga-rosa** [comment]
`picker` and `output` are implemented independently, so they don't exactly correspond to each other. So, in fact, the "which format color was picked up" is not retained inside the plugin.
This plugin even allows the user to define the picker and output. For example, you can create an output of rgba function. Because of this situation, it is difficult to implement a toggle like HEX -> RGB -> HSL -> HEX...

**Comment by gegoune** [comment]
Seems to be working fine, thank you!
